version: "3"
services:
  web:
    build: .
    links:
      - redis
    ports:
      - "1443:1443"
    environment:
      - REDIS_HOST=redis
      - FXA_REQUIRED=false
      - BASE_URL=send.ture.dev
      - MAX_FILE_SIZE=2684354560
      - NODE_ENV=production
  redis:
    image: redis:alpine
